### ISSUE TITLE
application/json REST endpoint not working

### ISSUE THREAD

**Issue by ianengelbrecht** [rogerhyam/wfo-plant-list#7]
Hi Roger, 

I'm trying to resolve WFO IDs in OpenRefine. I have a field in the dataset which contains the WFO ID. I go to 'Add column by fetching URLs', I set the expression to `'https://list.worldfloraonline.org/' + value` (value being the wfo id), and set the Accept header to application/json, but I'm getting html back (see attached file where I copy pasted one of the html responses). I can only think it has something to do with the redirect. 

[example.txt](https://github.com/user-attachments/files/17445785/example.txt)

I also tried calling the API using Talend (an in-browser equivalent of Postman, if you're not familiar with it), but it also doesn't seem to be able to follow the redirect, something about a limitation in Chrome. 

Then I tried the first curl example on the documentation page, `curl -I -H "Accept: application/json" https://list.worldfloraonline.org/wfo-0000615907`, which only returns headers, so I think the -I is meant to be a -L. This does return JSON, but the format is rather unfriendly to work with by having URLs as property names and arrays of {type,value} objects as values. 

I'd like to suggest simplifying this all quite drastically. Firstly to move the redirect logic to your server so that the client doesn't have to follow redirects. Then to return a simpler result JSON object with properties for name, author, id, source, synonyms, etc, whatever might be available on the html page for a species. If users need more detailed information they can use the jsonld, rdf, turtle, etc formats.  

Sorry that this turned into quite a dump, I hope it might be helpful feedback.

**Comment by rogerhyam** [comment]
The redirects are the standard method for doing semantic web compatible URIs with content negotiation. We have to have the redirects if we are to use one URL for an object but enable different clients to have the data in the format they want. This was defined by Tim Berners Lee back in 1998 as cool urls. All clients should be able to take a parameter like the curl -L to follow redirects.

I feel your pain with the long field names in the JSON but this is to make them cross compatible with the the RDF XML or JSON-LD versions of the data. The field names are globally unique so that you can mix that data in with anything. In a serialisation of RDF they become quite succinct. e.g. turtle where the namespaces can be split out.

https://list.worldfloraonline.org/sw_data.php?wfo=wfo-0000615907&format=turtle

I'd rather not redesign this as it is standards led. More application specific JSON can alway be retrieved from the GraphQL end point and tailored to specific needs. If there were a very clear use case for a simple GET -> JSON call then I could add that (like the Reconciliation API) but it would be a shallow layer on top of the GraphQL code anyhow!

Hope this helps.
